---
# list of applications to install
general:
  local_home: "{{ lookup('env','HOME') }}"

# homebrew applications
applications:
  - git
  - curl
  - wget
  - kubectl
  - kubernetes-helm
  - zsh
  - vim
  - terraform
  - pyenv
  - awscli

# homebrew cask applications
cask_applications:
  - google-chrome
  - docker
  - vagrant
  - 1password
  - virtualbox
  - spotify
  - google-drive-file-stream
  - visual-studio-code
  - skype
  - slack

downloads:

